name: CI Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest 
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]  
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies (make setup)
      run: make setup

    - name: Run tests (make test)
      run: make test

    - name: Run linter (make lint)
      run: make lint